<?php

namespace OCA\CrmConnector\Db;

use OCP\AppFramework\Db\Entity;
use \OCP\AppFramework\Db\QBMapper;
use OCP\DB\Exception;
use OCP\IDBConnection;
use OCP\IUser;

class CrmUserMapper extends QBMapper
{
    public function __construct(IDBConnection $db)
    {
        parent::__construct($db, CrmConnectorTypes::CRM_CONNECTOR_TABLE_USERS_NAME, CrmUser::class);
    }

    /**
     * @throws Exception
     */
    public function insertUser(Entity $entity): Entity
    {
        return parent::insertOrUpdate($entity); // TODO: Change the autogenerated stub
    }
}