<?php

namespace OCA\CrmConnector\Db;

use OCP\AppFramework\Db\Entity;
use \OCP\AppFramework\Db\QBMapper;
use OCP\IDBConnection;
use OCP\IUser;

class CrmUserMapper
{
    public function __construct(IDBConnection $db)
    {
        parent::__construct($db, CrmConnectorTypes::CRM_CONNECTOR_TABLE_USERS_NAME, CrmUser::class);
    }

    /**
     * @throws \OCP\DB\Exception
     */
    public function insertFile(Entity $entity): Entity
    {
        return parent::insert($entity); // TODO: Change the autogenerated stub
    }
}