<?php

namespace OCA\CrmConnector\Mapper;

use OCA\CrmConnector\Db\CrmConnectorTypes;
use OCA\CrmConnector\Db\CrmToken;
use OCP\AppFramework\Db\Entity;
use OCP\AppFramework\Db\QBMapper;
use OCP\DB\Exception;
use OCP\IDBConnection;

class CrmTokenMapper extends QBMapper
{
    public function __construct(IDBConnection $db)
    {
        parent::__construct($db, CrmConnectorTypes::CRM_CONNECTOR_TABLE_TOKENS_NAME, CrmToken::class);
    }

    /**
     * @param string $token
     * @return void $fetch
     * @throws Exception
     */
    public function getCrmTokenUserId(string $token)
    {
        $db = $this->db->getQueryBuilder();
        $result = $db->select('user_id')
            ->from($this->getTableName())
            ->where(
                $db->expr()->eq('token', $db->createNamedParameter($token, 'string'))
            )->execute();
        $fetch = $result->fetch();
        $result->closeCursor();
        return $fetch;
    }

    /**
     * @throws Exception
     */
    public function insertOrUpdate(Entity $entity): Entity
    {
        return parent::insertOrUpdate($entity); // TODO: Change the autogenerated stub
    }
}